name: ci
on: [push]

jobs:
  activate:
    runs-on: self-ubuntu-22.04
    if: |
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ready
  pytests:
    needs: activate
    runs-on: self-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installs and upgrades necessary packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest
      - name: tests
        run: |
          python3 -c"import sys; print(sys.path)"
          python3 -m pytest -s